# Generated by Django 5.2.1 on 2025-05-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_currency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
