# Generated by Django 5.2.1 on 2025-06-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_productimage_productspecification_repairservice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="operating_system",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
